### ISSUE TITLE
Client Error and call to https://www.larabug.com/

### ISSUE THREAD

**Issue by DonDiegoAA** [LaraBug/nova-larabug-tool#1]
I have this error
![larabug-error](https://user-images.githubusercontent.com/6011568/44752887-b93cbe80-ab1c-11e8-9501-2d8091cd7361.PNG)

In src / Utilities / Larabug.php, there is some key (LB_KEY, LB_PROJECT_KEY) and calls to https: //www.larabug.com/api/projects ...

![larabug-error-code](https://user-images.githubusercontent.com/6011568/44753095-4a139a00-ab1d-11e8-90f1-6634d547d9d9.PNG)

Why is that ?

**Comment by Cannonb4ll** [comment]
Ah, I see I forgot to add the part where you need to add the .env variable keys to the enviroment. Will do so now right away.

**Comment by Cannonb4ll** [comment]
Done, please re-read readme.

https://github.com/LaraBug/nova-larabug-tool/blob/master/README.md
