### ISSUE TITLE
Error on api 

### ISSUE THREAD

**Issue by shirshak55** [LaraBug/nova-larabug-tool#2]
<img width="1792" alt="screen shot 2018-09-05 at 9 51 19 am" src="https://user-images.githubusercontent.com/8097377/45070515-4bcaf800-b0f1-11e8-9030-496439ca171b.png">

```
Client error: `GET https://www.larabug.com/api/projects//exceptions?page=1` resulted in a `404 Not Found` response:
```

**Comment by shirshak55** [comment]
sry .env was not loaded

**Comment by Cannonb4ll** [comment]
Thats okay, glad you solved it! 👍
