### ISSUE TITLE
Getting a   [Symfony\Component\Process\Exception\RuntimeException]     The process has been signaled with signal "11".    

### ISSUE THREAD

**Issue by PilauGrice** [LaraBug/nova-larabug-tool#4]
Hi am Running 

Composer version 2.0.2 2020-10-25 23:03:59
PHP 7.4.11 (cli) (built: Oct  1 2020 23:30:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

Any ideas ?

**Comment by Cannonb4ll** [comment]
Error does not happen with me. Have you installed the latest version? Setup all the keys?

**Comment by PilauGrice** [comment]
Running laravel 8  the php artisan larabug:tests command works

**Comment by Cannonb4ll** [comment]
This is unrelated to this repository.

The tool works with me in the latest Laravel Nova version, please provide more information if you have any.
