### ISSUE TITLE
Api 404

### ISSUE THREAD

**Issue by ao-jhelmich** [LaraBug/nova-larabug-tool#5]
When opening the tool page in nova receiving the following error:

https://www.larabug.com/exception/YlK2xVCoMtdZcBj

Weird thing is, the error does get send to larabug.
So the config must be correct

Is the API down?

**Comment by mamedia-edv** [comment]
Can confirm! Same issue here!

**Comment by ao-jhelmich** [comment]
Is this tool deprecated? If so, please close the repo

**Comment by Cannonb4ll** [comment]
No, certainly not. Tool is in full development and working beautifully. If there's any error with this package for Nova, we'd accept any PR to fix/resolve this issue.

https://github.com/LaraBug/larabug-app
https://github.com/LaraBug/LaraBug

**Comment by ao-jhelmich** [comment]
Would like to reopen this issue, since the issue is still there.

Do you have an idea to what the issue is? Would like to solve this, making a pr wouldn't be a problem

**Comment by ao-jhelmich** [comment]
![image](https://user-images.githubusercontent.com/17061364/132831991-8682e92c-921e-42cb-a6dc-84684140b7dc.png)

Still same server error, from larabug.

see: https://www.larabug.com/exception/0GWqvTvvZMR9WSf

Any clue?

**Comment by Cannonb4ll** [comment]
I don't know what the issue is, if I would a fix would be easy to implement myself.

I haven't got the time to dive into that as of now. I'd recommend cloning it in your nova installation and try to see what the issue is.

**Comment by lloricode** [comment]
> ![image](https://user-images.githubusercontent.com/17061364/132831991-8682e92c-921e-42cb-a6dc-84684140b7dc.png)
> 
> Still same server error, from larabug.
> 
> see: https://www.larabug.com/exception/0GWqvTvvZMR9WSf
> 
> Any clue?

same as mine after installing this nova tool
